# Generated by Django 5.0.1 on 2024-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('expression', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('numerical_result', models.CharField(blank=True, max_length=255, null=True)),
                ('upper_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('x_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
