# Generated by Django 5.0.1 on 2024-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_api', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='bitmap',
            field=models.ImageField(null=True, upload_to='chat_images/'),
        ),
    ]
